### ISSUE TITLE
Updating versioned entity fails with "Parameter position is out of range"

### ISSUE THREAD

**Issue by dennislloydjr** [jruesga/phoenix-hibernate-dialect#3]
Given a versioned entity like this:

```
package com.ruesga.phoenix.jpa.entities;

import javax.persistence.*;
import java.io.Serializable;

@Entity(name="versioned")
@Table(name="VE", schema="T")
public class VersionedEntity implements Serializable {
  private static final long serialVersionUID = 1L;

  @Id
  @Column(name = "ID", nullable = false)
  private int id;

  @Version
  @Column(name = "VERSION")
  private int version;

  @Column(name = "FLD")
  private String field;

  public VersionedEntity() {
  }

  public int getId() {
    return id;
  }

  public void setId(int id) {
    this.id = id;
  }

  public int getVersion() {
    return version;
  }

  public void setVersion(int version) {
    this.version = version;
  }

  public String getField() {
    return field;
  }

  public void setField(String field) {
    this.field = field;
  }

  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + id;
    result = prime * result + version;
    result = prime * result + ((field == null) ? 0 : field.hashCode());
    return result;
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj)
      return true;
    if (obj == null)
      return false;
    if (getClass() != obj.getClass())
      return false;
    VersionedEntity other = (VersionedEntity) obj;
    if (id != other.id) {
      return false;
    } else if (version != other.version) {
      return false;
    } else if (field == null && other.field != null) {
      return false;
    } else if (field != null && !field.equals(other.field)) {
      return false;
    } else {
      return true;
    }
  }

  @Override
  public String toString() {
    return "VersionedEntity [id=" + id + ", version=" + version + ", field=" + field + "]";
  }
}
```

An existing record in the database:
`UPSERT INTO T.VE (ID, VERSION, FLD) VALUES (20001, 1, 'FIELD-VALUE')`

And a test case like this:
```
    @Test
    public void test402_UpdateVersionedEntity() {
        TypedQuery<VersionedEntity> q = em.createQuery("select v from versioned v where v.id = :id", VersionedEntity.class);
        q.setParameter("id", 20001);
        VersionedEntity v = q.getSingleResult();

        em.getTransaction().begin();

        v.setField("NEW FIELD VALUE");
        em.persist(v);

        em.getTransaction().commit();

        q = em.createQuery("select v from versioned v where v.id = :id", VersionedEntity.class);
        q.setParameter("id", 20001);
        VersionedEntity updated = q.getSingleResult();
        Assert.assertEquals(v.getField(), updated.getField());
    }
```

The following exception is received:
```
javax.persistence.RollbackException: Error while committing the transaction

	at org.hibernate.internal.ExceptionConverterImpl.convertCommitException(ExceptionConverterImpl.java:77)
	at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:71)
	at com.ruesga.phoenix.dialect.PhoenixDialectTest.test402_UpdateVersionedEntity(PhoenixDialectTest.java:641)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: could not update: [com.ruesga.phoenix.jpa.entities.VersionedEntity#20001]
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:149)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:157)
	at org.hibernate.internal.ExceptionConverterImpl.convertCommitException(ExceptionConverterImpl.java:61)
	... 28 more
Caused by: org.hibernate.exception.GenericJDBCException: could not update: [com.ruesga.phoenix.jpa.entities.VersionedEntity#20001]
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:47)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:111)
	at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:3227)
	at org.hibernate.persister.entity.AbstractEntityPersister.updateOrInsert(AbstractEntityPersister.java:3077)
	at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:3457)
	at org.hibernate.action.internal.EntityUpdateAction.execute(EntityUpdateAction.java:145)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:589)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:463)
	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:337)
	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:39)
	at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1437)
	at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:493)
	at org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:3207)
	at org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:2413)
	at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:473)
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.beforeCompletionCallback(JdbcResourceLocalTransactionCoordinatorImpl.java:156)
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.access$100(JdbcResourceLocalTransactionCoordinatorImpl.java:38)
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.commit(JdbcResourceLocalTransactionCoordinatorImpl.java:231)
	at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:68)
	... 27 more
Caused by: java.sql.SQLException: ERROR 2003 (INT04): Parameter position is out of range. Can't set parameter at index 4, 3 bind parameters are defined
	at org.apache.phoenix.exception.SQLExceptionCode$Factory$1.newException(SQLExceptionCode.java:488)
	at org.apache.phoenix.exception.SQLExceptionInfo.buildException(SQLExceptionInfo.java:150)
	at org.apache.phoenix.jdbc.PhoenixPreparedStatement.setParameter(PhoenixPreparedStatement.java:122)
	at org.apache.phoenix.jdbc.PhoenixPreparedStatement.setInt(PhoenixPreparedStatement.java:391)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.setInt(NewProxyPreparedStatement.java:171)
	at org.hibernate.type.descriptor.sql.IntegerTypeDescriptor$1.doBind(IntegerTypeDescriptor.java:46)
	at org.hibernate.type.descriptor.sql.BasicBinder.bind(BasicBinder.java:74)
	at org.hibernate.type.AbstractStandardBasicType.nullSafeSet(AbstractStandardBasicType.java:279)
	at org.hibernate.type.AbstractStandardBasicType.nullSafeSet(AbstractStandardBasicType.java:274)
	at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:3170)
	... 43 more
```

**Comment by dennislloydjr** [comment]
The problem seems to stem from Hibernate adding a WHERE clause to the UPDATE statement. The WHERE clause restricts the row being updated by the @Id column and the @Version column. After generating the UDPATE statement, Hibernate attempts to add the parameter values for the WHERE clause to the generated PreparedStatement.

This fails because the dialect rewrites the UPDATE statement and removes the WHERE clause. 

I think in this case, the UPSERT ... VALUES should become an UPSERT ... SELECT.

**Comment by dennislloydjr** [comment]
I think I'll have a Pull Request for this shortly. From looking at the code, it doesn't look like where columns in an update are being properly handled either. I'm not sure I have time to tackle that issue today though. If I don't, I'll open up another issue for it.

**Comment by dennislloydjr** [comment]
Pull Request is here: https://github.com/jruesga/phoenix-hibernate-dialect/pull/4

**Comment by jruesga** [comment]
@dennislloydjr thanks for the PR

**Comment by dennislloydjr** [comment]
Thanks for picking it up and responding so quickly to the PR!

**Comment by jruesga** [comment]
Version 0.0.4 was published to github releases (https://jcenter.bintray.com/com/ruesga/phoenix/phoenix-hibernate-dialect/) and JCenter (https://github.com/jruesga/phoenix-hibernate-dialect/releases). In Maven Central, it will be up in a few hours.
